name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: nanasess/setup-chromedriver@v1

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
         node-version: '16.x'

    - name: npm install and test
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
        npm install
        npm test
